import type { ParsedCv, CvSection } from "./cv-parse.ts";

/**
 * Re-emits a parsed CV as LaTeX in the template it came from.
 *
 * The source `.tex` of the imported PDF is gone, and a PDF has no editable text
 * structure, so "same format, different words" cannot be done by patching. It
 * can be done by regenerating: the layout comes from this template and only the
 * words come from the parsed content. That is why the parser keeps structure
 * rather than text.
 *
 * The template is Jake Gutierrez's widely-used resume class, which is what the
 * imported PDF was built with — same section rule, same small-caps headings,
 * same two-column subheadings.
 */

/**
 * LaTeX's ten special characters. Left unescaped, a single "%" in a bullet
 * comments out the rest of the line and a "&" is an alignment error — either
 * way the document silently stops compiling, which is a miserable thing to
 * hand someone as a copy-paste block.
 */
const LATEX_ESCAPES: Record<string, string> = {
  "\\": "\\textbackslash{}",
  "&": "\\&",
  "%": "\\%",
  $: "\\$",
  "#": "\\#",
  _: "\\_",
  "{": "\\{",
  "}": "\\}",
  "~": "\\textasciitilde{}",
  "^": "\\textasciicircum{}",
};

export function escapeLatex(value: string): string {
  return (
    value
      // One pass over every special at once. Escaping them in sequence meant a
      // backslash became \textbackslash{} and then the braces of that very
      // replacement were escaped again, producing \textbackslash\{\} — a
      // broken command in the middle of the document.
      .replace(/[\\&%$#_{}~^]/g, (character) => LATEX_ESCAPES[character] ?? character)
      // Not special, just the template's own conventions, so regenerated text
      // matches what is already in the document. A bare "|" in text mode does
      // not render as a pipe at all — the template writes it in math mode, and
      // the project titles ("Trakzi | Next.js, React") depend on it.
      .replace(/\|/g, "$|$")
      .replace(/–/g, "--")
      .replace(/—/g, "---")
  );
}

const PREAMBLE = String.raw`% Regenerated by EQ from your imported CV.
% Template: Jake Gutierrez's resume (MIT licence) — the one this CV was built with.
\documentclass[letterpaper,11pt]{article}

\usepackage{latexsym}
\usepackage[empty]{fullpage}
\usepackage{titlesec}
\usepackage{marvosym}
\usepackage[usenames,dvipsnames]{color}
\usepackage{verbatim}
\usepackage{enumitem}
\usepackage[hidelinks]{hyperref}
\usepackage{fancyhdr}
\usepackage[english]{babel}
\usepackage{tabularx}
\input{glyphtounicode}

\pagestyle{fancy}
\fancyhf{}
\fancyfoot{}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}

\addtolength{\oddsidemargin}{-0.5in}
\addtolength{\evensidemargin}{-0.5in}
\addtolength{\textwidth}{1in}
\addtolength{\topmargin}{-.5in}
\addtolength{\textheight}{1.0in}

\urlstyle{same}
\raggedbottom
\raggedright
\setlength{\tabcolsep}{0in}

\titleformat{\section}{
  \vspace{-4pt}\scshape\raggedright\large
}{}{0em}{}[\color{black}\titlerule \vspace{-5pt}]

\pdfgentounicode=1

\newcommand{\resumeItem}[1]{
  \item\small{
    {#1 \vspace{-2pt}}
  }
}

\newcommand{\resumeSubheading}[4]{
  \vspace{-2pt}\item
    \begin{tabular*}{0.97\textwidth}[t]{l@{\extracolsep{\fill}}r}
      \textbf{#1} & #2 \\
      \textit{\small#3} & \textit{\small #4} \\
    \end{tabular*}\vspace{-7pt}
}

\newcommand{\resumeProjectHeading}[2]{
    \item
    \begin{tabular*}{0.97\textwidth}{l@{\extracolsep{\fill}}r}
      \small#1 & #2 \\
    \end{tabular*}\vspace{-7pt}
}

\renewcommand\labelitemii{$\vcenter{\hbox{\tiny$\bullet$}}$}

\newcommand{\resumeSubHeadingListStart}{\begin{itemize}[leftmargin=0.15in, label={}]}
\newcommand{\resumeSubHeadingListEnd}{\end{itemize}}
\newcommand{\resumeItemListStart}{\begin{itemize}}
\newcommand{\resumeItemListEnd}{\end{itemize}\vspace{-5pt}}
`;

/** "Technologies: ..." — a label and a colon, not prose that happens to contain one. */
const LABELLED_LINE = /^[^:]{1,30}\s*:\s/;

function renderSection(section: CvSection): string {
  const lines: string[] = [`\\section{${escapeLatex(section.heading)}}`];

  if (section.entries.length > 0) {
    lines.push("  \\resumeSubHeadingListStart");
    for (const entry of section.entries) {
      // A subheading with no second row is a project-style heading; the
      // template has a separate macro for exactly that shape.
      if (entry.subtitle === undefined) {
        lines.push(
          `    \\resumeProjectHeading`,
          `      {\\textbf{${escapeLatex(entry.title)}}}{${escapeLatex(entry.meta ?? "")}}`,
        );
      } else {
        lines.push(
          `    \\resumeSubheading`,
          `      {${escapeLatex(entry.title)}}{${escapeLatex(entry.meta ?? "")}}`,
          `      {${escapeLatex(entry.subtitle)}}{${escapeLatex(entry.subtitleMeta ?? "")}}`,
        );
      }
      if (entry.bullets.length > 0) {
        lines.push("      \\resumeItemListStart");
        for (const bullet of entry.bullets) {
          lines.push(`        \\resumeItem{${escapeLatex(bullet.text)}}`);
        }
        lines.push("      \\resumeItemListEnd");
      }
    }
    lines.push("  \\resumeSubHeadingListEnd");
  }

  // Two different things arrive as loose lines. A "Technologies: ..." line is
  // skills content and belongs in the template's compact labelled block; an
  // orphan bullet ("Cloud Computing with AWS Certificate") was a bullet in the
  // original and has to stay one, or Other Achievements silently loses its
  // markers on the way back out.
  const labelled = section.looseLines.filter((line) => LABELLED_LINE.test(line));
  const looseBullets = section.looseLines.filter((line) => !LABELLED_LINE.test(line));

  if (labelled.length > 0) {
    lines.push(
      " \\begin{itemize}[leftmargin=0.15in, label={}]",
      "    \\small{\\item{",
    );
    for (const line of labelled) {
      const [label, ...rest] = line.split(/\s*:\s*/);
      lines.push(`     \\textbf{${escapeLatex(label)}}{: ${escapeLatex(rest.join(": "))}} \\\\`);
    }
    lines.push("    }}", " \\end{itemize}");
  }

  if (looseBullets.length > 0) {
    lines.push("  \\resumeSubHeadingListStart", "      \\resumeItemListStart");
    for (const line of looseBullets) {
      lines.push(`        \\resumeItem{${escapeLatex(line)}}`);
    }
    lines.push("      \\resumeItemListEnd", "  \\resumeSubHeadingListEnd");
  }

  return lines.join("\n");
}

export function renderCvLatex(cv: ParsedCv): string {
  const header = [
    "\\begin{center}",
    `    \\textbf{\\Huge \\scshape ${escapeLatex(cv.name)}} \\\\ \\vspace{1pt}`,
    `    \\small ${escapeLatex(cv.contactLine)}`,
    "\\end{center}",
  ].join("\n");

  return [
    PREAMBLE,
    "\\begin{document}",
    "",
    header,
    "",
    ...cv.sections.map(renderSection),
    "",
    "\\end{document}",
    "",
  ].join("\n");
}

export interface BulletChange {
  section: string;
  entry: string;
  before: string;
  after: string;
}

/**
 * What a rewrite actually changed, bullet by bullet.
 *
 * Shown in full and never summarised: the point of the diff is that an invented
 * claim is visible rather than buried, and a summary is exactly where one would
 * hide. Structure is compared position-by-position because a rewrite may only
 * reword bullets, never add, remove or reorder them.
 */
export function diffCvBullets(before: ParsedCv, after: ParsedCv): BulletChange[] {
  const changes: BulletChange[] = [];
  for (const [sectionIndex, section] of before.sections.entries()) {
    const afterSection = after.sections[sectionIndex];
    if (afterSection === undefined) continue;
    for (const [entryIndex, entry] of section.entries.entries()) {
      const afterEntry = afterSection.entries[entryIndex];
      if (afterEntry === undefined) continue;
      for (const [bulletIndex, bullet] of entry.bullets.entries()) {
        const afterBullet = afterEntry.bullets[bulletIndex];
        if (afterBullet === undefined) continue;
        if (afterBullet.text === bullet.text) continue;
        changes.push({
          section: section.heading,
          entry: entry.title,
          before: bullet.text,
          after: afterBullet.text,
        });
      }
    }
  }
  return changes;
}

/**
 * Applies rewritten bullets onto a parsed CV by position.
 *
 * Rejects anything that would change the CV's shape — a rewrite is allowed to
 * change wording and nothing else. Adding a bullet is how an invented job would
 * get in, and the shape check is what makes that impossible rather than merely
 * discouraged.
 */
export function applyRewrittenBullets(
  cv: ParsedCv,
  replacements: { sectionIndex: number; entryIndex: number; bulletIndex: number; text: string }[],
): ParsedCv {
  const next: ParsedCv = {
    ...cv,
    sections: cv.sections.map((section) => ({
      ...section,
      entries: section.entries.map((entry) => ({
        ...entry,
        bullets: entry.bullets.map((bullet) => ({ ...bullet })),
      })),
      looseLines: [...section.looseLines],
    })),
  };

  for (const replacement of replacements) {
    const bullet =
      next.sections[replacement.sectionIndex]?.entries[replacement.entryIndex]?.bullets[
        replacement.bulletIndex
      ];
    if (bullet === undefined) {
      throw new Error(
        `Rewrite targets a bullet that does not exist (${replacement.sectionIndex}/${replacement.entryIndex}/${replacement.bulletIndex}).`,
      );
    }
    bullet.text = replacement.text;
  }
  return next;
}
